import React from "react";

function Consent({ setParticipantId, setGroupNumber, setShowPromptSelectionPage}) {
  const startExperiment = (formSubmit) => {
    formSubmit.preventDefault();
    setParticipantId(formSubmit.target.participantId.value);
    setGroupNumber(formSubmit.target.groupNumber.value);
    setShowPromptSelectionPage(true);
  };

  return (
    <div>
      <div className="header">
      <h1>START</h1>
      </div>
      <div className="consent">
      <h3>Introduction:</h3>
        <p>You are invited to participate in a research study that aims to compare the performance of different Large Language Models (LLMs) in generating contextually appropriate and relevant responses to user-selected questions. This study is conducted to gain insights into the strengths and weaknesses of LLMs in handling diverse query types and providing accurate and useful emotional responses as information to users.</p>
        
        <h3>Purpose of the Study:</h3>
        <p>The purpose of this study is to evaluate the responses generated by different LLMs, such as OpenAI's GPT-3 and potentially others, to understand their effectiveness in providing contextually appropriate and relevant responses. This research is for enhancing user satisfaction and trust in LLM-based applications.</p>
        
        <h3>Study Procedures:</h3>
        <p>If you agree to participate, you will be asked to interact with an application that utilizes LLMs to generate responses to user queries. You will be presented with a series of questions or prompts and asked to evaluate the responses provided by the LLMs based on their relevance, accuracy, and emotional appropriateness.</p>
        
        <h3>Risks and Benefits:</h3>
        <p>There are no known risks associated with participating in this study. However, you may benefit from gaining insights into the capabilities of LLMs in generating contextually appropriate and relevant responses.</p>
        
        <h3>Confidentiality:</h3>
        <p>Your participation in this study is confidential. Your identity will not be linked to any data collected during the study, and all data will be anonymized and aggregated for analysis purposes.</p>
        
        <h3>Voluntary Participation:</h3>
        <p>Participation in this study is voluntary, and you may withdraw at any time without penalty. Your decision to participate or not will not affect your current or future relationship with the researchers or the organization.</p>
      </div>
      <h2>Session Info</h2>
      <form className="form" onSubmit={startExperiment}>
        <label>
          Participant ID: 
          <input type="number" name="participantId" min="0" required />
        </label>
        <br />
        <label>
          Group Number: 
          <input type="number" name="groupNumber" min="0" max="1" defaultValue="0"required />
        </label>
        <br />
        <button type="submit">Agree</button>
      </form>
    </div>
  );
}

export default Consent;